- hosts: fastapi01
  become: true
  tasks:
    - name: Install deps
      ansible.builtin.package:
        name:
          - git
          - nginx
          - python3-venv
          - python3-pip
          - acl
        state: present

    - name: Create user for app
      ansible.builtin.user:
        name: fastapi
#        shell: /bin/bash
#        groups: admins,developers
#        append: yes

    - name: Create dir for app
      ansible.builtin.file:
        path: /var/fastapi/
        mode: "755"
        owner: fastapi
        group: fastapi
        state: directory

    - name: Read-write git checkout from github
      become: true
      become_user: fastapi
      ansible.builtin.git:
        repo: https://gist.github.com/21456f4797100376f67443920e5d5145.git
        dest: /var/fastapi/
        version: main

    - name: Create venv for app
      ansible.builtin.file:
        path: /opt/venv_fastapi/
        mode: "755"
        owner: fastapi
        group: fastapi
        state: directory

    - name: Setup venv
      become: true
      become_user: fastapi
      ansible.builtin.pip:
        requirements: /var/fastapi/requirements.txt
        virtualenv: /opt/venv_fastapi/
        virtualenv_command: /usr/bin/python3 -m venv

    - name: Template service file
      ansible.builtin.template:
        src: ../data/systemd_fastapi.conf.j2
        dest: /etc/systemd/system/fastapi.service
        owner: root
        group: root
        mode: "644"

    - name: Start service fastapi
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: fastapi

    - name: Template nginx config file
      ansible.builtin.template:
        src: ../data/nginx_fastapi.conf.j2
        dest: /etc/nginx/sites-available/my_fastapi_app
        owner: root
        group: root
        mode: "644"

    - name: Link nginx config file
      ansible.builtin.file:
        src: /etc/nginx/sites-available/my_fastapi_app
        dest: /etc/nginx/sites-enabled/my_fastapi_app
        owner: root
        group: root
        mode: "644"
        state: link

    - name: Reload service nginx, in all cases
      ansible.builtin.systemd_service:
        name: nginx.service
        state: reloaded
